ДЗ 1
bshelkhonov/2019-2-Track-Frontend-B-Shelkhonov pull request #1
Opened 2019-09-30 17:25 UTC by bshelkhonov

# Домашнее задание №1
Прошу @martinkomitsky, @chexex или @priver проверить его
Что было сделано:
1) функция convertBytesToHuman.js и тесты
2) функция correctSentence.js
3) функция nonUniqueElements.jsggit

2019-09-30 17:32 UTC, chexex requested changes
Удалить файл package-lock.json (мешает сборке в трэвисе)

2019-09-30 17:32 UTC, chexex commented on pull_request_template.md
> +3) функция nonUniqueElements.js
Подразумевается, что `pull_request_template.md` – это шаблон, поэтому лучше не писать в этом файле, что конкретно было сделано, иначе придется его переделывать для каждого дз :)

2019-09-30 17:40 UTC, bshelkhonov commented on pull_request_template.md
> +3) функция nonUniqueElements.js
Файл удалил. Трэвис пишет, что всё ок

2019-10-01 14:30 UTC, chexex commented on .gitignore
> +pull_request_template.md
Темплейт нужен :)

2019-10-01 14:30 UTC, chexex commented on .gitignore
> +pull_request_template.md
```suggestion

```

2019-10-01 14:30 UTC, chexex approved these changes

2019-10-01 14:31 UTC, chexex commented
Функции +
Тесты +
Сборка +

Спасибо за работу,
12 баллов

2019-10-01 14:33 UTC, merged