HW2-try-one
bshelkhonov/2019-2-Track-Frontend-B-Shelkhonov pull request #2
Opened 2019-10-13 22:58 UTC by bshelkhonov

Прошу @priver @martinkomitsky @chexex проверить дз номер 2.

Пока что не очень разобрался, как сделать так, чтобы выглядело не вырвиглазно, и как делать кнопочки. 

Как это выглядит в действительности: https://bshelkhonov.github.io/2019-2-Track-Frontend-B-Shelkhonov/

Сделано: отправка сообщений, сохранение их в localStorage. Чтобы удалить историю сообщений, введите /dev/clear, или сделайте через средства разработчика в браузере.

2019-10-14 10:48 UTC, priver requested changes
![image](https://user-images.githubusercontent.com/1700074/66746018-4e1d8b00-ee89-11e9-805d-582d915a6519.png)
вот это не похоже на то что в макете

2019-10-14 10:48 UTC, priver commented on web-components/src/components/MessageForm.js
> +      const newMessage = document.createElement('div');
нужно создать отдельный компонент для сообщения

2019-10-14 10:48 UTC, priver commented on web-components/src/components/MessageForm.js
> +    for (const key in localStorage) {
Нужно создать массив messages и записать его в localStorage целиком в один ключ. Иначе мы весь сторадж под один чат заняли.

Как поведет себя программа, если я запишу в localStorage ключ myKey? length увеличится на 1, а элемента с ключем [length - 1] в сторадже не будет

не нужно придумывать костыли с isInteger и сортировкой

2019-10-14 10:48 UTC, priver commented on web-components/src/index.html
> +  <div class="head-container">
Шапка должна быть web-компонентом

2019-10-14 22:57 UTC, bshelkhonov commented
Прошу @priver @martinkomitsky @chexex перепроверить дз номер 2. Вроде бы почти всё исправил

2019-10-21 18:02 UTC, bshelkhonov commented
![image](https://user-images.githubusercontent.com/52068583/67230501-147af000-f446-11e9-850b-cd79dd0067b2.png)
![image](https://user-images.githubusercontent.com/52068583/67230546-1f358500-f446-11e9-96c5-92330af962c2.png)

2019-10-23 15:03 UTC, priver requested changes

2019-10-23 15:03 UTC, priver commented on web-components/src/components/MessageForm.js
> +const splitter = 'R2P6kf';
это что такое?

2019-10-23 15:03 UTC, priver commented on web-components/src/components/MessageForm.js
> +    stringArray += `${splitter}${time}${separator}${msgText}`;
нужно записать в localStorage массив, а не строку со странным сепаратором

2019-10-23 15:03 UTC, priver commented on web-components/src/components/Message.js
> +    this.$input.setAttribute(name, newValue);
у класса нет такого поля `$input`
этот метод вероятно вообще не нужен

2019-10-24 06:49 UTC, chexex commented
https://travis-ci.org/bshelkhonov/2019-2-Track-Frontend-B-Shelkhonov/builds/600876013#L221-L231
Исправить эти ошибки

2019-10-24 21:28 UTC, bshelkhonov commented
Прошу @priver @martinkomitsky @chexex перепроверить дз номер 2 ещё раз

2019-10-25 12:40 UTC, priver approved these changes
10 баллов

2019-10-25 12:40 UTC, merged